name: app
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9


  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  firebase_storage: ^11.7.4
  image_picker: ^1.1.0
  random_string: ^2.3.1
  get: ^4.6.6
  cloud_firestore: ^4.17.2
  fluttertoast: ^8.2.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/inbox-svgrepo-com.svg
    - assets/images/lines-football-field.jpg
    - assets/images/table-tennis.jpg
    - assets/images/ssfix.png
    - assets/fields/Fivas.jpg
    - assets/fields/redd.jpg
    - assets/fields/hokky.jpg
    - assets/icons/back-svgrepo-com.svg


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
